# Generated by Django 4.1.4 on 2022-12-13 05:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.CharField(choices=[('In stock', 'In stock'), ('On order', 'On order'), ('Receipt expected', 'Receipt expected'), ('Not available', 'Not available'), ('Not produced', 'Not produced')], default='In stock', max_length=16),
        ),
    ]
