# Generated by Django 4.1.4 on 2022-12-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='position',
            new_name='status',
        ),
    ]
