# Generated by Django 4.1.4 on 2022-12-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_status_product_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='position',
            new_name='status',
        ),
    ]
